# Базовый образ Nginx
FROM nginx:alpine

# Копируем статические файлы в директорию Nginx
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/
