
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # Порт для приложений
      - "15672:15672"  # Порт для управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: adminka
      POSTGRES_PASSWORD: huivamanedb
      POSTGRES_DB: planingworksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql://adminka:huivamanedb@db:5432/planingworksdb
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql://adminka:huivamanedb@db:5432/planingworksdb
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql://adminka:huivamanedb@db:5432/planingworksdb
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
